# Generated by Django 5.2.1 on 2025-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('bot', 'LIA')], default='user', max_length=10),
        ),
    ]
